- name: Update and Upgrade Packages
  hosts: all
  become: yes  # Ensures the commands run with root privileges
  tasks:
    - name: Update the apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

